### ISSUE TITLE
前段源码

### ISSUE THREAD

**Issue by shawnjian520** [vainhope/vain-admin#1]
请问下，前段架构源码有吗？

**Comment by vainhope** [comment]
在web分支  git clone -b web https://github.com/vainhope/vain-admin.git 就好了

**Comment by shawnjian520** [comment]
好的，谢谢


| |
zhangjian
邮箱：zhangjian19900304@163.com
|

Signature is customized by Netease Mail Master

在2019年02月27日 20:08，vainhope 写道：

在web分支 git clone -b web https://github.com/vainhope/vain-admin.git 就好了
